/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.login;

import javax.swing.JPanel;

import business.EcoSystem;
import business.Network.Network;
import business.Enterprise.Enterprise;
import business.Organization.Organization;
import business.Role.Role;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author apara
 */
public class LoginJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    public EcoSystem system;

    /**
     * Creates new form LoginJPanel
     */
    public LoginJPanel(JPanel workArea, EcoSystem system) {
        initComponents();
        this.workArea = workArea;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(510, 340, 150, 50);

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        add(txtUserName);
        txtUserName.setBounds(580, 230, 130, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("User Name:");
        add(jLabel1);
        jLabel1.setBounds(426, 230, 140, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Password:");
        add(jLabel2);
        jLabel2.setBounds(435, 280, 120, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Welcome to the system");
        add(jLabel3);
        jLabel3.setBounds(400, 160, 420, 50);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword);
        txtPassword.setBounds(580, 280, 132, 34);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/login/login.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, -50, 1980, 1180);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String userName = txtUserName.getText();
        char[] passwordCharArray = txtPassword.getPassword();

        String password = String.valueOf(passwordCharArray);

        UserAccount authenticatedUser = system.getUserAccountDirectory().authenticateUser(userName, password);

        if (authenticatedUser != null) {

            JOptionPane.showMessageDialog(null, "Login successful.");

            ArrayList<Network> networkList = system.getNetworkList();
            Network network = null;
            for (Network n : networkList) {
                network = n;
            }

            Enterprise enterprise = authenticatedUser.getEnterprise();
            Organization organization = authenticatedUser.getOrganization();
            Role role = authenticatedUser.getRole();

            CardLayout cardLayout = (CardLayout) workArea.getLayout();
            JPanel jP = role.createWorkArea(workArea, system, network, enterprise, organization, authenticatedUser);
            workArea.add(jP, "jpanel");
            cardLayout.show(workArea, "jpanel");
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private UserAccount authenticateUser() {

        return null;

    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
