/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ambulance;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.Organization;
import business.Stakeholders.Ambulance;
import business.UserAccount.UserAccount;
import javax.swing.JPanel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class ambulanceDetailsJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    Organization organization;
    Enterprise enterprise;
    Network network;
    EcoSystem ecoSystem;
    UserAccount account;

    /**
     * Creates new form ambulanceDetailsJPanel
     */
    public ambulanceDetailsJPanel(JPanel workArea, EcoSystem ecoSystem, Network network, Enterprise enterprise, Organization organization, UserAccount account) {
        initComponents();
        this.workArea = workArea;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.ecoSystem = ecoSystem;

        populateAmbTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrivers = new javax.swing.JTable();
        btnLogout2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 102));
        setLayout(null);

        tblDrivers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Driver Name", "Ambulance Number", "Pickup Address"
            }
        ));
        jScrollPane1.setViewportView(tblDrivers);

        add(jScrollPane1);
        jScrollPane1.setBounds(190, 240, 640, 290);

        btnLogout2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout2.setForeground(new java.awt.Color(0, 0, 102));
        btnLogout2.setText("Log Out");
        btnLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout2ActionPerformed(evt);
            }
        });
        add(btnLogout2);
        btnLogout2.setBounds(10, 10, 100, 37);

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/ambulance/amb.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1980, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
        // TODO add your handling code here:

        workArea.remove(this);
        ((java.awt.CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnLogout2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDrivers;
    // End of variables declaration//GEN-END:variables

    private void populateAmbTable() {
        ArrayList<Ambulance> ambulanceList = ecoSystem.getAmbulanceDirectory().getAmbulanceList();

        DefaultTableModel model = (DefaultTableModel) tblDrivers.getModel();
        model.setRowCount(0);

        for (Ambulance a : ambulanceList) {
            Object[] row = new Object[3];
            row[0] = a.getDriverName();
            row[1] = a.getAmbulanceNumber();
            row[2] = a.getLocation();

            model.addRow(row);
        }
    }
}
