/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ambulance;

import business.EcoSystem;
import business.Organization.EmergencyOrg;
import business.Organization.Organization;
import business.WorkQueue.EmergencyWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.EmergencyUnit.EmergencyJPanel;

/**
 *
 * @author meetb
 */
public class assignAmbulanceJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    EcoSystem ecoSystem;
    EmergencyOrg emergencyOrg;
    EmergencyWorkRequest emergencyWorkRequest;
    //PatientDirectory patientDirectory;

    /**
     * Creates new form assignAmbulanceJPanel
     */
    public assignAmbulanceJPanel(JPanel workArea, EcoSystem ecoSystem) {
        initComponents();
        this.workArea = workArea;
        this.ecoSystem = ecoSystem;
        //this.patientDirectory = ecoSystem.getPatientDirectory();

        populateRequestTable();

    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();

        model.setRowCount(0);

        for (Organization organization : ecoSystem.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof EmergencyOrg) {
                this.emergencyOrg = (EmergencyOrg) organization;
                break;
            }
        }

        for (WorkRequest wr : emergencyOrg.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof EmergencyWorkRequest) {
                EmergencyWorkRequest emerWrkReq = (EmergencyWorkRequest) wr;
                Object[] row = new Object[4];

                row[0] = emerWrkReq.getEmergencyRequestId();
                row[1] = emerWrkReq.getPatient().getPatientId();
                row[2] = emerWrkReq.getPatient().getPatientName();
                row[3] = emerWrkReq.getStatus();

                model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 102));
        setLayout(null);

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RequestID", "Patient ID", "Patient Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblPatients);

        add(jScrollPane1);
        jScrollPane1.setBounds(130, 220, 630, 220);

        btnAssign.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAssign.setForeground(new java.awt.Color(0, 0, 102));
        btnAssign.setText("Assign Pickup");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign);
        btnAssign.setBounds(340, 450, 150, 60);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(30, 30, 72, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/ambulance/amb.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1980, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblPatients.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String requestId = tblPatients.getModel().getValueAt(selectedRow, 0).toString();
        for (WorkRequest wr : emergencyOrg.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof EmergencyWorkRequest) {
                EmergencyWorkRequest emergencyWorkRequest = (EmergencyWorkRequest) wr;
                if (emergencyWorkRequest.getEmergencyRequestId().equals(requestId)) {
                    this.emergencyWorkRequest = emergencyWorkRequest;
                }
                emergencyWorkRequest.setStatus("Processing");
                JOptionPane.showMessageDialog(this, "Pickup assigned!");
            }
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        EmergencyJPanel Panel = new EmergencyJPanel(workArea, ecoSystem);
        workArea.removeAll();
        workArea.add("EmergencyJPanel", Panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);           // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPatients;
    // End of variables declaration//GEN-END:variables
}
