/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.EquipmentUnit;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Equipment.Equipment;
import business.Equipment.EquipmentDirectory;
import business.JSONUtil.Store;
import business.Network.Network;
import business.Organization.BillingOrg;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.BillingWorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meetb
 */
public class EquipmentMainJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    Enterprise enterprise;
    EcoSystem ecosystem;
    EquipmentDirectory equipmentList;
    Equipment equipment;
    Network network;
    UserAccount account;
    Organization organization;

    /**
     * Creates new form EquipmentMainJPanel
     */
    public EquipmentMainJPanel(JPanel workArea, EcoSystem ecosystem, Network network, Enterprise enterprise, Organization organization, UserAccount account) {
        initComponents();
        this.workArea = workArea;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.equipmentList = ecosystem.getEquipmentList();
        this.network = network;
        this.account = account;
        this.organization = organization;

        populateEquipTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEquipmentId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        txtEquipmentRequestId = new javax.swing.JTextField();
        txtnoOfUnits = new javax.swing.JTextField();
        txtequipmentPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tblEqipment = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtEquipmentName = new javax.swing.JTextField();
        btnLogout2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setLayout(null);
        add(txtEquipmentId);
        txtEquipmentId.setBounds(850, 350, 215, 22);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 102));
        btnAdd.setText("Add Equipment");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(724, 630, 160, 27);
        add(txtEquipmentRequestId);
        txtEquipmentRequestId.setBounds(850, 450, 215, 22);
        add(txtnoOfUnits);
        txtnoOfUnits.setBounds(850, 550, 215, 22);
        add(txtequipmentPrice);
        txtequipmentPrice.setBounds(850, 500, 215, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Equipment ID:");
        add(jLabel2);
        jLabel2.setBounds(680, 360, 110, 21);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Equipment Request ID:");
        add(jLabel3);
        jLabel3.setBounds(611, 460, 170, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Equipment Name:");
        add(jLabel4);
        jLabel4.setBounds(649, 410, 130, 21);

        btnRequest.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnRequest.setForeground(new java.awt.Color(0, 0, 102));
        btnRequest.setText("Request Bill");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest);
        btnRequest.setBounds(950, 630, 140, 27);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity:");
        add(jLabel5);
        jLabel5.setBounds(700, 560, 70, 21);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Equipment Unit");
        add(jLabel1);
        jLabel1.setBounds(750, 80, 350, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Price:");
        add(jLabel6);
        jLabel6.setBounds(693, 510, 80, 21);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Equipment ID", "Equipment Name", "Price", "Quantity"
            }
        ));
        tblEqipment.setViewportView(jTable1);

        add(tblEqipment);
        tblEqipment.setBounds(520, 140, 699, 160);
        add(txtEquipmentName);
        txtEquipmentName.setBounds(850, 400, 215, 22);

        btnLogout2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnLogout2.setForeground(new java.awt.Color(0, 0, 102));
        btnLogout2.setText("Log Out");
        btnLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout2ActionPerformed(evt);
            }
        });
        add(btnLogout2);
        btnLogout2.setBounds(10, 10, 96, 37);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/EquipmentUnit/final bg.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 0, 1980, 1100);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String equipmentId = txtEquipmentId.getText();
        String equipmentName = txtEquipmentName.getText();
        String equipmentReqID = txtEquipmentRequestId.getText();
        double equipmentPrice = Double.parseDouble(txtequipmentPrice.getText());
        String totalQuantity = txtnoOfUnits.getText();

        //Equipment equipment = new Equipment(equipmentId, equipmentName, equipmentReqID, equipmentPrice, totalQuantity);
        //System.out.println(equipment);
        ecosystem.getEquipmentList().addNewEquipment(equipmentId, equipmentName, equipmentReqID, equipmentPrice, totalQuantity);
        Store.save(ecosystem);
        JOptionPane.showMessageDialog(this, "Equipment added successfully.");

        txtEquipmentId.setText("");
        txtEquipmentName.setText("");
        txtEquipmentRequestId.setText("");
        txtequipmentPrice.setText("");
        txtnoOfUnits.setText("");

        populateEquipTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String equipmentId = jTable1.getModel().getValueAt(selectedRow, 0).toString();
        for (Equipment e : this.equipmentList.getEquipmentList()) {
            if (e.getEquipmentID().equals(equipmentId)) {
                this.equipment = e;
            }
        }

        BillingWorkRequest request = new BillingWorkRequest();
        request.setSender(account);
        request.setStatus("Sent");
        request.setEquipment(this.equipment);

        Organization org = null;
        for (Organization organization : ecosystem.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof BillingOrg) {
                org = organization;
                ecosystem.getOrganizationDirectory().getOrganizationList().remove(org);
                org.getWorkQueue().addWorkRequest(request);
                //account.getWorkQueue().addWorkRequest(request);
                ecosystem.getOrganizationDirectory().getOrganizationList().add(org);
                Store.save(ecosystem);
                break;
            }
        }

        JOptionPane.showMessageDialog(null, "Request sent!");
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
        // TODO add your handling code here:

        workArea.remove(this);
        ((java.awt.CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnLogout2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblEqipment;
    private javax.swing.JTextField txtEquipmentId;
    private javax.swing.JTextField txtEquipmentName;
    private javax.swing.JTextField txtEquipmentRequestId;
    private javax.swing.JTextField txtequipmentPrice;
    private javax.swing.JTextField txtnoOfUnits;
    // End of variables declaration//GEN-END:variables

    private void populateEquipTable() {
        ArrayList<Equipment> equipmentList = ecosystem.getEquipmentList().getEquipmentList();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Equipment e : equipmentList) {
            Object[] row = new Object[4];
            row[0] = e.getEquipmentID();
            row[1] = e.getEquipmetName();
            row[2] = e.getTotalCost();
            row[3] = e.getAvailableQuant();
            model.addRow(row);
        }
    }
}
