/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountingUnit;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Organization.BillingOrg;
import business.Organization.Organization;
import business.WorkQueue.BillingWorkRequest;
import business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apara
 */
public class AccountingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountingJPanel
     */
    JPanel workArea;
    Enterprise enterprise;
    EcoSystem ecoSystem;

    BillingOrg billingOrg;
    BillingWorkRequest billingWorkRequest;

    public AccountingJPanel(JPanel workArea, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.workArea = workArea;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        //this.billingWorkRequest = billingWorkRequest;
        populateRequestTable();
    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (Organization organization : ecoSystem.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof BillingOrg) {
                this.billingOrg = (BillingOrg) organization;
                break;
            }
        }

        for (WorkRequest wr : billingOrg.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof BillingWorkRequest) {
                BillingWorkRequest billWrkReq = (BillingWorkRequest) wr;
                Object[] row = new Object[7];

                row[0] = billWrkReq.getEquipment().getEquipmentID();
                row[1] = billWrkReq.getSender().getUsername();
                row[2] = billWrkReq.getEquipment().getEquipmetName();
                row[3] = billWrkReq;
                row[4] = billWrkReq.getEquipment().getTotalCost();
                row[5] = billWrkReq.getEquipment().getAvailableQuant();
                row[6] = billWrkReq.getStatus();

                model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblEqipment = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Equipment ID", "Sender", "Equipment Name", "Billing Request ID", "Price", "Quantity", "Status"
            }
        ));
        tblEqipment.setViewportView(jTable1);

        add(tblEqipment);
        tblEqipment.setBounds(455, 190, 831, 183);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EQUIPMENT BILLING");
        add(jLabel1);
        jLabel1.setBounds(729, 130, 290, 32);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Generate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(534, 400, 140, 27);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Notify Equipment Admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(1008, 400, 220, 27);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(6, 6, 100, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AccountingUnit/final bg.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1980, 1100);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:     

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String billingRequestId = jTable1.getModel().getValueAt(selectedRow, 0).toString();
        for (WorkRequest wr : billingOrg.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof BillingWorkRequest) {
                BillingWorkRequest billWrkReq = (BillingWorkRequest) wr;
                if (billWrkReq.getBillingRequestId().equals(billingRequestId)) {
                    this.billingWorkRequest = billWrkReq;
                }
                billWrkReq.setStatus("Processing");
                JOptionPane.showMessageDialog(this, "Bill generated!");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String billingRequestId = jTable1.getModel().getValueAt(selectedRow, 0).toString();
        for (WorkRequest wr : billingOrg.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof BillingWorkRequest) {
                BillingWorkRequest billWrkReq = (BillingWorkRequest) wr;
                if (billWrkReq.getBillingRequestId().equals(billingRequestId)) {
                    this.billingWorkRequest = billWrkReq;
                }
                billWrkReq.setStatus("Completed");
                JOptionPane.showMessageDialog(this, "Notified the Equipment Admin!");
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        ((java.awt.CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblEqipment;
    // End of variables declaration//GEN-END:variables
}
